---
deployment:
  tasks:
      # - export DEPLOYPATH=/home/c1987705c/public_html/
      # - /bin/cp * $DEPLOYPATH
      - export DEPLOYPATH=/home/c1987705c/public_html/admin/
      # - /bin/cp * $DEPLOYPATH
      - /bin/cp -r /home/c1987705c/public_html/public_html/admin/ $DEPLOYPATH
